AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 50
    MemorySize: 5000
  Api:
    BinaryMediaTypes:
      - image/png
      - image/jpg
      - image/jpeg

Resources:
  DogBreedFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        DogBreed:
          Type: Api
          Properties:
            Path: /dog_breed
            Method: post
    Metadata:
      Dockerfile: ./Dockerfile
      DockerContext: ./app
      DockerTag: python3.8-v1

Outputs:
  DogBreedApi:
    Description: "API Gateway endpoint URL for Prod stage for Inference function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/classify_digit/"
  DogBreedFunction:
    Description: "DogBreed Lambda Function ARN"
    Value: !GetAtt DogBreedFunction.Arn
  DogBreedFunctionIamRole:
    Description: "Implicit IAM Role created for DogBreed function"
    Value: !GetAtt DogBreedFunction.Arn
